package com.fullviewsdk

import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import io.fullview.fullview_sdk.Fullview
import io.fullview.fullview_sdk.FullviewSessionState
import io.fullview.fullview_sdk.HostType
import io.fullview.fullview_sdk.Region

/**
 * TurboModule over the native Fullview Android SDK. `NativeFullviewSdkSpec` is
 * generated by codegen from src/NativeFullviewSdk.ts.
 */
class FullviewSdkModule(reactContext: ReactApplicationContext) : NativeFullviewSdkSpec(reactContext) {

  private var sdk: Fullview? = null

  override fun attach(promise: Promise) {
    if (sdk != null) {
      promise.resolve(null)
      return
    }
    val activity = reactApplicationContext.currentActivity
    if (activity == null) {
      promise.reject("ATTACH_ERROR", "No current activity; call attach() once the app is mounted.")
      return
    }
    activity.runOnUiThread {
      try {
        sdk = Fullview().also { it.attach(activity, HostType.REACT_NATIVE) }
        promise.resolve(null)
      } catch (t: Throwable) {
        promise.reject("ATTACH_ERROR", t)
      }
    }
  }

  override fun register(
    region: String,
    organisationId: String,
    userId: String,
    deviceId: String,
    name: String,
    email: String,
    promise: Promise
  ) {
    val s = sdk ?: return promise.reject("REGISTER_ERROR", "attach() must be called before register().")
    try {
      s.register(
        organisationId = organisationId,
        userId = userId,
        deviceId = deviceId,
        name = name,
        email = email,
        region = Region.valueOf(region.uppercase()),
        additionalConfig = emptyMap()
      )
      promise.resolve(null)
    } catch (t: Throwable) {
      promise.reject("REGISTER_ERROR", t)
    }
  }

  override fun logout(promise: Promise) {
    val s = sdk ?: return promise.reject("LOGOUT_ERROR", "attach() not called.")
    s.logout()
    promise.resolve(null)
  }

  override fun requestCoBrowse(promise: Promise) {
    val s = sdk ?: return promise.reject("REQUEST_COBROWSE_ERROR", "attach() not called.")
    s.requestCoBrowse()
    promise.resolve(null)
  }

  override fun cancelCoBrowseRequest(promise: Promise) {
    val s = sdk ?: return promise.reject("CANCEL_COBROWSE_REQUEST_ERROR", "attach() not called.")
    s.cancelCoBrowseRequest()
    promise.resolve(null)
  }

  override fun getPositionInCoBrowseQueue(promise: Promise) {
    promise.resolve(sdk?.positionInCoBrowseQueue?.replayCache?.lastOrNull() ?: -1)
  }

  /** Same vocabulary as iOS so the JS mapping in sdk-module.tsx works on both. */
  override fun getState(promise: Promise) {
    val state = sdk?.sessionState?.replayCache?.lastOrNull()
    promise.resolve(
      when (state) {
        is FullviewSessionState.CO_BROWSE_ACTIVE -> "CO_BROWSE_ACTIVE"
        is FullviewSessionState.CO_BROWSE_INVITATION -> "CO_BROWSE_INVITATION"
        is FullviewSessionState.CO_BROWSE_REQUESTED -> "CO_BROWSE_REQUESTED"
        else -> "IDLE"
      }
    )
  }

  companion object {
    const val NAME = NativeFullviewSdkSpec.NAME
  }
}
